#pragma once
#include "fig_1_04.h"
#include "fig_1_05.h"
#include "fig_1_07.h"
#include "fig_1_10.h"
#include "fig_1_11.h"
#include "fig_1_12.h"
#include "sidebar_functor.h"
#include "sidebar_lambda.h"